/**
 * Init subcommand — generates a .skill-lint.yaml config file with sensible defaults.
 * Calls detectFormat() to auto-detect the repo format and includes it in the output.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getDefaults } from './config.js';
import { detectFormat } from './detect-format.js';
import type { RepoFormat } from './types.js';

const CONFIG_FILENAME = '.skill-lint.yaml';

/** Options for the init subcommand. */
export type InitOptions = {
  force?: boolean;
};

/** Build the YAML config string based on detected format. */
export function buildConfigYaml(detectedFormat: RepoFormat): string {
  const lines: string[] = [
    '# .skill-lint.yaml — generated by claude-skill-lint init',
    `# Detected format: ${detectedFormat}`,
    'skills_root: "."',
    'default_level: 0',
  ];

  if (detectedFormat !== 'legacy-commands') {
    lines.push(`format: ${detectedFormat}`);
  }

  lines.push(
    '',
    'models: [opus, sonnet, haiku]',
    '',
    'tools:',
    '  mcp_pattern: "mcp__*"',
    '  custom: []',
    '',
    'limits:',
    '  max_file_size: 15360',
    '',
    'ignore:',
    '  - "**/README.md"',
    '  - "**/CLAUDE.md"',
    '  - "node_modules/**"',
    '',
    'graph:',
    '  warn_orphans: true',
    '  detect_cycles: true',
    '  detect_duplicates: true',
    '',
  );

  return lines.join('\n');
}

/**
 * Run the init subcommand.
 * @returns exit code (0 = success)
 */
export function runInit(rootDir: string, options: InitOptions = {}): number {
  const configPath = join(rootDir, CONFIG_FILENAME);

  // AC-4: If config already exists and no --force, warn and exit 0
  if (existsSync(configPath) && !options.force) {
    process.stderr.write(
      `Warning: ${CONFIG_FILENAME} already exists. Use --force to overwrite.\n`,
    );
    return 0;
  }

  // AC-1: Call detectFormat() with a default config (no format override)
  const detectedFormat = detectFormat(rootDir, getDefaults());

  // Build and write the config file
  const yaml = buildConfigYaml(detectedFormat);
  writeFileSync(configPath, yaml, 'utf-8');

  // AC-6: Success message to stderr
  process.stderr.write(`Created ${configPath}\n`);
  process.stderr.write('Run `claude-skill-lint lint .` to validate your files.\n');

  return 0;
}
